In [1]:
import numpy as np

In [2]:
r_a = [10, 20, 30, 5, 5]
r_d = [10, 15, 15, 10, 15]
t = [60, 60, 60, 180, 30]

In [3]:
a_t = np.cumsum([r_a[i] * t[i] for i in range(5)])

In [4]:
d_t = np.cumsum([r_d[i] * t[i] for i in range(5)])

In [5]:
a_t

array([ 600, 1800, 3600, 4500, 4650])

In [6]:
d_t

array([ 600, 1500, 2400, 4200, 4650])

In [7]:
np.cumsum(t)

array([ 60, 120, 180, 360, 390])

In [8]:
a_t - d_t

array([   0,  300, 1200,  300,    0])

In [9]:
delay = [((a_t[i] + a_t[i+1]) * t[i+1] / 2) - ((d_t[i] + d_t[i+1]) * t[i+1] / 2) for i in range(4)]

In [10]:
delay = [0] + delay

In [11]:
delay = np.cumsum(delay)

In [12]:
delay

array([     0.,   9000.,  54000., 189000., 193500.])

In [14]:
ave_d = [delay[i]/a_t[i] for i in range(5)]

In [15]:
ave_d

[0.0, 5.0, 15.0, 42.0, 41.61290322580645]