In [6]:
import numpy as np
from math import exp
from math import factorial

In [ ]:
#problem 2

In [29]:
r_a = [10, 20, 30, 5, 5]
r_d = [10, 15, 15, 10, 15]
t = [60, 60, 60, 180, 30]

In [30]:
a_t = np.cumsum([r_a[i] * t[i] for i in range(5)])

In [31]:
d_t = np.cumsum([r_d[i] * t[i] for i in range(5)])

In [32]:
a_t

array([ 600, 1800, 3600, 4500, 4650])

In [6]:
d_t

array([ 600, 1500, 2400, 4200, 4650])

In [7]:
np.cumsum(t)

array([ 60, 120, 180, 360, 390])

In [8]:
a_t - d_t

array([   0,  300, 1200,  300,    0])

In [9]:
delay = [((a_t[i] + a_t[i+1]) * t[i+1] / 2) - ((d_t[i] + d_t[i+1]) * t[i+1] / 2) for i in range(4)]

In [10]:
delay = [0] + delay

In [11]:
delay = np.cumsum(delay)

In [12]:
delay

array([     0.,   9000.,  54000., 189000., 193500.])

In [14]:
ave_d = [delay[i]/a_t[i] for i in range(5)]

In [15]:
ave_d

[0.0, 5.0, 15.0, 42.0, 41.61290322580645]

In [ ]:
#problem 6

In [5]:
exp(-20)

2.061153622438558e-09

In [14]:
l = 20
t = 1
n = 5
exp(-l*t)*(l*t)**n/factorial(n)

5.496409659836154e-05

In [25]:
l = 20
t = 1
n = 5
1-np.sum([exp(-l*t)*(l*t)**i/factorial(i) for i in range(5)])

0.9999830552560699

In [ ]:
#problem 3

In [47]:
r_a = [30, 30]
r_d = [20, 40]
t = [2, 2]

In [48]:
a_t = np.cumsum([r_a[i] * t[i] for i in range(2)])

In [49]:
d_t = np.cumsum([r_d[i] * t[i] for i in range(2)])

In [50]:
a_t

array([ 60, 120])

In [51]:
d_t

array([ 40, 120])

In [53]:
a_t - d_t

array([20,  0])

In [55]:
delay = [((a_t[i] + a_t[i+1]) * t[i+1] / 2) - ((d_t[i] + d_t[i+1]) * t[i+1] / 2) for i in range(1)]

In [56]:
delay = [0] + delay

In [57]:
delay = np.cumsum(delay)

In [58]:
delay

array([ 0., 20.])

In [63]:
ave_d = [delay[i]/a_t[i] for i in range(2)]

In [64]:
ave_d

[0.0, 0.16666666666666666]

In [68]:
ave_d[-1]*60

10.0

In [ ]:
#problem 4

In [81]:
r_a = [6, 6, 6]
r_d = [0, 15, 10]
t = [2, 1, 0.75]

In [87]:
a_t = np.cumsum([r_a[i] * t[i] for i in range(len(t))])

In [91]:
d_t = np.cumsum([r_d[i] * t[i] for i in range(len(t))])

In [92]:
a_t

array([12. , 18. , 22.5])

In [93]:
d_t

array([ 0. , 15. , 22.5])

In [94]:
a_t - d_t

array([12.,  3.,  0.])

In [96]:
delay = [((a_t[i] + a_t[i+1]) * t[i+1] / 2) - ((d_t[i] + d_t[i+1]) * t[i+1] / 2) for i in range(len(t)-1)]

In [97]:
delay = [0] + delay

In [98]:
delay = np.cumsum(delay)

In [99]:
delay

array([0.   , 7.5  , 8.625])

In [102]:
ave_d = [delay[i]/a_t[i] for i in range(len(t))]

In [103]:
ave_d

[0.0, 0.4166666666666667, 0.38333333333333336]

In [104]:
ave_d[-1]*60

23.0

In [ ]:
#problem 5

In [150]:
r_a = [45, 45]
r_d = [30, 60]
t = [1, 1]

In [151]:
a_t = np.cumsum([r_a[i] * t[i] for i in range(len(t))])

In [152]:
d_t = np.cumsum([r_d[i] * t[i] for i in range(len(t))])

In [153]:
a_t

array([45, 90])

In [154]:
d_t

array([30, 90])

In [155]:
a_t - d_t

array([15,  0])

In [156]:
delay = [((a_t[i] + a_t[i+1]) * t[i+1] / 2) - ((d_t[i] + d_t[i+1]) * t[i+1] / 2) for i in range(len(t)-1)]

In [157]:
delay = [0] + delay

In [158]:
delay = np.cumsum(delay)

In [159]:
delay

array([0. , 7.5])

In [160]:
ave_d = [delay[i]/a_t[i] for i in range(len(t))]

In [161]:
ave_d

[0.0, 0.08333333333333333]

In [162]:
ave_d[-1]*60

5.0

In [163]:
r_a = [10, 10]
r_d = [0, 30]
t = [2, 1]

In [164]:
a_t = np.cumsum([r_a[i] * t[i] for i in range(len(t))])

In [165]:
d_t = np.cumsum([r_d[i] * t[i] for i in range(len(t))])

In [166]:
a_t

array([20, 30])

In [167]:
d_t

array([ 0, 30])

In [168]:
a_t - d_t

array([20,  0])

In [169]:
delay = [((a_t[i] + a_t[i+1]) * t[i+1] / 2) - ((d_t[i] + d_t[i+1]) * t[i+1] / 2) for i in range(len(t)-1)]

In [170]:
delay = [0] + delay

In [171]:
delay = np.cumsum(delay)

In [172]:
delay

array([ 0., 10.])

In [173]:
ave_d = [delay[i]/a_t[i] for i in range(len(t))]

In [174]:
ave_d

[0.0, 0.3333333333333333]

In [175]:
ave_d[-1]*60

20.0