In [1]:
import numpy as np
from math import exp
from math import factorial

In [2]:
#problem 2

In [3]:
r_a = [10, 20, 30, 5, 5]
r_d = [10, 15, 15, 10, 15]
t = [60, 60, 60, 180, 30]

In [4]:
a_t = np.cumsum([r_a[i] * t[i] for i in range(5)])

In [5]:
d_t = np.cumsum([r_d[i] * t[i] for i in range(5)])

In [6]:
a_t

array([ 600, 1800, 3600, 4500, 4650])

In [7]:
d_t

array([ 600, 1500, 2400, 4200, 4650])

In [8]:
np.cumsum(t)

array([ 60, 120, 180, 360, 390])

In [9]:
a_t - d_t

array([   0,  300, 1200,  300,    0])

In [10]:
delay = [((a_t[i] + a_t[i+1]) * t[i+1] / 2) - ((d_t[i] + d_t[i+1]) * t[i+1] / 2) for i in range(4)]

In [11]:
delay = [0] + delay

In [12]:
delay = np.cumsum(delay)

In [13]:
delay

array([     0.,   9000.,  54000., 189000., 193500.])

In [14]:
ave_d = [delay[i]/a_t[i] for i in range(5)]

In [15]:
ave_d

[0.0, 5.0, 15.0, 42.0, 41.61290322580645]

In [16]:
#problem 6

In [17]:
exp(-20)

2.061153622438558e-09

In [18]:
l = 20
t = 1
n = 5
exp(-l*t)*(l*t)**n/factorial(n)

5.496409659836154e-05

In [19]:
l = 20
t = 1
n = 5
1-np.sum([exp(-l*t)*(l*t)**i/factorial(i) for i in range(5)])

0.9999830552560699

In [20]:
#problem 3

In [21]:
r_a = [30, 30]
r_d = [20, 40]
t = [2, 2]

In [22]:
a_t = np.cumsum([r_a[i] * t[i] for i in range(2)])

In [23]:
d_t = np.cumsum([r_d[i] * t[i] for i in range(2)])

In [24]:
a_t

array([ 60, 120])

In [25]:
d_t

array([ 40, 120])

In [26]:
a_t - d_t

array([20,  0])

In [27]:
delay = [((a_t[i] + a_t[i+1]) * t[i+1] / 2) - ((d_t[i] + d_t[i+1]) * t[i+1] / 2) for i in range(1)]

In [28]:
delay = [0] + delay

In [29]:
delay = np.cumsum(delay)

In [30]:
delay

array([ 0., 20.])

In [31]:
ave_d = [delay[i]/a_t[i] for i in range(2)]

In [32]:
ave_d

[0.0, 0.16666666666666666]

In [33]:
ave_d[-1]*60

10.0

In [34]:
#problem 4

In [35]:
r_a = [6, 6, 6]
r_d = [0, 15, 10]
t = [2, 1, 0.75]

In [36]:
a_t = np.cumsum([r_a[i] * t[i] for i in range(len(t))])

In [37]:
d_t = np.cumsum([r_d[i] * t[i] for i in range(len(t))])

In [38]:
a_t

array([12. , 18. , 22.5])

In [39]:
d_t

array([ 0. , 15. , 22.5])

In [40]:
a_t - d_t

array([12.,  3.,  0.])

In [41]:
delay = [((a_t[i] + a_t[i+1]) * t[i+1] / 2) - ((d_t[i] + d_t[i+1]) * t[i+1] / 2) for i in range(len(t)-1)]

In [42]:
delay = [0] + delay

In [43]:
delay = np.cumsum(delay)

In [44]:
delay

array([0.   , 7.5  , 8.625])

In [45]:
ave_d = [delay[i]/a_t[i] for i in range(len(t))]

In [46]:
ave_d

[0.0, 0.4166666666666667, 0.38333333333333336]

In [47]:
ave_d[-1]*60

23.0

In [48]:
#problem 5

In [49]:
r_a = [45, 45]
r_d = [30, 60]
t = [1, 1]

In [50]:
a_t = np.cumsum([r_a[i] * t[i] for i in range(len(t))])

In [51]:
d_t = np.cumsum([r_d[i] * t[i] for i in range(len(t))])

In [52]:
a_t

array([45, 90])

In [53]:
d_t

array([30, 90])

In [54]:
a_t - d_t

array([15,  0])

In [55]:
delay = [((a_t[i] + a_t[i+1]) * t[i+1] / 2) - ((d_t[i] + d_t[i+1]) * t[i+1] / 2) for i in range(len(t)-1)]

In [56]:
delay = [0] + delay

In [57]:
delay = np.cumsum(delay)

In [58]:
delay

array([0. , 7.5])

In [59]:
ave_d = [delay[i]/a_t[i] for i in range(len(t))]

In [60]:
ave_d

[0.0, 0.08333333333333333]

In [61]:
ave_d[-1]*60

5.0

In [62]:
r_a = [10, 10]
r_d = [0, 30]
t = [2, 1]

In [63]:
a_t = np.cumsum([r_a[i] * t[i] for i in range(len(t))])

In [64]:
d_t = np.cumsum([r_d[i] * t[i] for i in range(len(t))])

In [65]:
a_t

array([20, 30])

In [66]:
d_t

array([ 0, 30])

In [67]:
a_t - d_t

array([20,  0])

In [68]:
delay = [((a_t[i] + a_t[i+1]) * t[i+1] / 2) - ((d_t[i] + d_t[i+1]) * t[i+1] / 2) for i in range(len(t)-1)]

In [69]:
delay = [0] + delay

In [70]:
delay = np.cumsum(delay)

In [71]:
delay

array([ 0., 10.])

In [72]:
ave_d = [delay[i]/a_t[i] for i in range(len(t))]

In [73]:
ave_d

[0.0, 0.3333333333333333]

In [74]:
ave_d[-1]*60

20.0