In [1]:
from math import factorial
import numpy as np

In [2]:
def erlangB(c, r):
    B = 1 # B(0, r) = 1
    for i in range(1, c+1): # i from 1 to c
        B = r * B / (i + r * B)
        #print(i, r, B) # print intermediate results eoau 
    return B

In [3]:
def erlangC(c, r):
    B = erlangB(c, r)
    return c * B / (c - r + r * B)

# Problem 3

In [4]:
c = 400
r = 360
1 - erlangC(c, r)

0.9767133242295406

In [5]:
c = 450
r = [360]
for i in range(5):
    r.append(r[-1] * 1.05)
print(r)

[360, 378.0, 396.90000000000003, 416.74500000000006, 437.5822500000001, 459.4613625000001]


In [6]:
C = [1 - erlangC(c, i) for i in r]
print(C)

[0.9999971803782105, 0.999815931275941, 0.9947032998948981, 0.931138048098909, 0.5562709637779182, -0.6631122396115139]


# Problem 4

In [7]:
lam = 8
mu = 2
r = lam/mu
c = [i for i in range(1,15)]

In [8]:
C = [(i, round(1-erlangC(i,r),3)) for i in c]

In [9]:
for i in range(len(C)):
    print(f'{C[i][0]} & {round(C[i][1],4)} \\\\')

1 & -3.0 \\
2 & -1.667 \\
3 & -0.684 \\
4 & 0.0 \\
5 & 0.446 \\
6 & 0.715 \\
7 & 0.865 \\
8 & 0.941 \\
9 & 0.976 \\
10 & 0.991 \\
11 & 0.997 \\
12 & 0.999 \\
13 & 1.0 \\
14 & 1.0 \\


# Problem 5 (3.50)

## 5 (b)

In [10]:
c = 2
lam = 10
mu = 4
r = lam / mu
rho = r / c
K = 6 + c
print(r, rho, K)

2.5 1.25 8


In [11]:
n = r**c * (1 - rho**(K - c + 1))
d = factorial(c)*(1-rho)
s = sum([r**i/factorial(i) for i in range(c)])
p_0 = 1 / (n/d + s)
print(p_0)

0.019761031906033785


In [12]:
p_K = lam**K / (c**(K-c) * factorial(c) * mu**K) * p_0
print(p_K)

0.2355698574308608


# Problem 6 (3.50)

## 5 (a)

In [13]:
c = 4
lam = 30
mu = 1/4*60
r = lam / mu
rho = r / c
print(mu, r, rho)

15.0 2.0 0.5


In [14]:
p_4 = erlangB(c,r)
print(p_4)

0.09523809523809523


## 5 (a)

In [15]:
p_2 = erlangB(2,r)
p_6 = erlangC(6,r)
print(p_2, p_4, p_6)

0.4 0.09523809523809523 0.01801801801801802


In [16]:
p_c = np.array([p_2,p_4,p_6])
C_c = np.array([1e4,2e4,3e4])
t_c = C_c/(0.5*lam*(1-p_c)+lam*p_c)
print(t_c, t_c/24)

[ 476.19047619 1217.39130435 1964.60176991] [19.84126984 50.72463768 81.85840708]


In [17]:
for i in range(len(p_c)):
    print(f'{round(p_c[i],3)} & {round(t_c[i]/24,3)} \\\\')

0.4 & 19.841 \\
0.095 & 50.725 \\
0.018 & 81.858 \\


# 7

## 7 (a)

In [18]:
c = 4
lam = 20
mu = 5
K = 7
r = lam / mu
rho = r / c
print(r, rho)

4.0 1.0


In [19]:
n = r**c * (K - c + 1)
d = factorial(c)
s = sum([r**i/factorial(i) for i in range(c)])
p_0 = 1 / (n/d + s)
print(p_0)

0.015075376884422112


In [20]:
n = []
p_n = []
N = [i for i in range(c)]
p_N = [lam**i / (factorial(i) * mu**i) * p_0 for i in N]
n = n + N
p_n = p_n + p_N
print(n)
print(p_n)

[0, 1, 2, 3]
[0.015075376884422112, 0.06030150753768845, 0.1206030150753769, 0.16080402010050251]


In [21]:
N = [i for i in range(c,K+1)]
p_N = [lam**i / (c**(i-c) * factorial(c) * mu**i) * p_0 for i in N] 
n = n + N
p_n = p_n + p_N

In [22]:
for i in range(len(p_n)):
    print(f'{n[i]} & {round(p_n[i],4)} \\\\')

0 & 0.0151 \\
1 & 0.0603 \\
2 & 0.1206 \\
3 & 0.1608 \\
4 & 0.1608 \\
5 & 0.1608 \\
6 & 0.1608 \\
7 & 0.1608 \\


## 7 (b)

In [23]:
sum(p_n[:5])

0.5175879396984925

## 7 (c)

In [24]:
s = [(i-c)*p_n[i] for i in range(c+1,K+1)]
L_q = sum(s)
print(s, L_q)

[0.16080402010050251, 0.32160804020100503, 0.4824120603015075] 0.964824120603015


## 7 (d)

In [25]:
lam_eff = lam*(1-p_n[-1])
print(lam_eff)

16.78391959798995


In [26]:
W_q = L_q / lam_eff
print(W_q)

0.05748502994011976


# 8

## 8 (a)

In [27]:
R = np.array([[0.1, 0.6, 0.2, 0], [0, 0, 0.1, 0.8], [0, 0.1, 0, 0.8], [0, 0, 0, 0]])

In [28]:
gamma = np.array([30, 0, 0, 0])

In [29]:
mu = np.array([120, 30, 10, 30])

In [30]:
#np.linalg.inv(np.identity(4)-R)

In [31]:
lam = gamma.dot(np.linalg.inv(np.identity(4)-R))
print(lam)

[33.33333333 20.87542088  8.75420875 23.7037037 ]


In [32]:
r = lam/mu
print(r)

[0.27777778 0.69584736 0.87542088 0.79012346]


In [33]:
L = lam/(mu-lam)
L[0] = r[0]
print(L)
print(sum(L))

[0.27777778 2.28782288 7.02702703 3.76470588]
13.357333565386527


In [34]:
W = sum(L)/gamma[0]
print(W)
print(W*60)

0.44524445217955094
26.714667130773055


In [35]:
L_q = lam*lam/mu/(mu-lam)
L_q[0] = 0
print(L_q)

[0.         1.59197552 6.15160615 2.97458243]


In [36]:
W_q = L_q/lam
print(W_q)

[0.         0.07626076 0.7027027  0.1254902 ]


# 9 (Problem 5.14)

## 9 (a)

In [37]:
R = np.array([[0.3, 0.5], [1, 0]])

In [38]:
gamma = np.array([2, 0])

In [39]:
mu = np.array([2, 3])
c = [6, 2]

In [40]:
lam = gamma.dot(np.linalg.inv(np.identity(2)-R))
print(lam)

[10.  5.]


## 9 (b)

In [41]:
r = lam/mu
print(r)

[5.         1.66666667]


In [42]:
rho = r/c
print(rho)

[0.83333333 0.83333333]


In [43]:
p_0 = [0,0]
for j in range(len(c)):
    n = r[j]**c[j]
    d = factorial(c[j])*(1-rho[j])
    s = sum([r[j]**i/factorial(i) for i in range(c[j])])
    p_0[j] = 1 / (n/d + s)
p_0 = np.array(p_0)
print(p_0)

[0.00451213 0.09090909]


In [44]:
L_q = r**c*rho/np.array([factorial(i) for i in c])/(1-rho)/(1-rho)*p_0
print(L_q)

[2.93758225 3.78787879]


In [45]:
L = L_q + r
print(L)
print(sum(L))

[7.93758225 5.45454545]
13.392127706848528


In [46]:
W = sum(L)/gamma[0]
print(W)
print(W*60)

6.696063853424264
401.76383120545586


In [47]:
W_q = L_q/lam
print(W_q)

[0.29375823 0.75757576]


In [48]:
lam[0]*0.2

2.0000000000000004

In [49]:
W_n = L/lam
print(W_n)

[0.79375823 1.09090909]


# 10

## 10 (a)

In [50]:
R = np.array([[0, 1, 0, 0], [0.2, 0, 0.7, 0], [0, 0, 0, 1], [0.1, 0, 0.1, 0]])

In [51]:
gamma = np.array([10, 0, 0, 0])

In [52]:
mu = np.array([15, 15, 12, 12])
c = np.array([1, 1, 1, 1])

In [53]:
lam = gamma.dot(np.linalg.inv(np.identity(4)-R))
print(lam)

[13.84615385 13.84615385 10.76923077 10.76923077]


In [54]:
names = ['A','B','C','D']
l = [f'$\lambda_{names[i]}={round(lam[i],3)}$, ' for i in range(len(names))]
o = ''
for i in range(len(l)):
    o += l[i]
print(o)

$\lambda_A=13.846$, $\lambda_B=13.846$, $\lambda_C=10.769$, $\lambda_D=10.769$, 


In [55]:
0.6 * lam[-1]

6.461538461538461

## 10 (b)

In [56]:
r = lam/mu
print(r)

[0.92307692 0.92307692 0.8974359  0.8974359 ]


In [57]:
names = ['A','B','C','D']
l = [f'$r_{names[i]}={round(lam[i],3)}/{round(mu[i],3)}={round(r[i],3)}$, ' for i in range(len(names))]
o = ''
for i in range(len(l)):
    o += l[i]
print(o)

$r_A=13.846/15=0.923$, $r_B=13.846/15=0.923$, $r_C=10.769/12=0.897$, $r_D=10.769/12=0.897$, 


In [58]:
rho = r/c
print(rho)

[0.92307692 0.92307692 0.8974359  0.8974359 ]


In [59]:
L = rho / (1 - rho)
print(L)
print(sum(L))

[12.   12.    8.75  8.75]
41.50000000000001


## 10 (c)

In [60]:
W = sum(L)/gamma[0]
print(W)

4.15


In [61]:
sum([0, 0.1, 0, 0.2 + 0.6]*lam)

10.0